.tag-hog: &tag-hog
  tags:
     - hog

.tag-sr: &tag-sr
  tags:
     - docker

.only-default: &only-default
  only:
    refs:
      - merge_requests
      - master # or name of the default official branch
  except:
    variables:
      - $CI_COMMIT_REF_NAME =~ /^test\/.*$/i
      - $CI_MERGE_REQUEST_TITLE =~ /^Draft:.*$/ && $CI_COMMIT_MESSAGE !~ /^RESOLVE_WIP:/

etroc-sim-job:
  variables:
    GIT_STRATEGY: clone
  <<: *only-default
  <<: *tag-hog
  stage: user_pre
  script: "make -C src/etroc"

dataformat-update-job:
  variables:
    GIT_STRATEGY: clone
  <<: *only-default
  <<: *tag-hog
  stage: user_pre
  script:
    - "git submodule update --init -- regmap"
    - "make -C src/etroc/configs && git diff --exit-code"

registers-update-job:
  variables:
    GIT_STRATEGY: clone
  <<: *only-default
  <<: *tag-hog
  stage: user_pre
  script: "make reg && git checkout registers/ipbus_decode_etl_test_fw.vhd && git diff --exit-code"
