gen:etl_test_fw_master:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: etl_test_fw
      INTERMEDIATE_BUILD: 0

gen:etl_test_fw_devel:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: etl_test_fw
      INTERMEDIATE_BUILD: 1
